AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EFS"
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  ImageId:
    Type: String
    Default: ami-0a590ca28046d073e
  SubnetId:
    Type: String
    Default: subnet-0a50e521730d08e8c
  VpcId:
    Type: String
    Default: vpc-0ee039fa4f7f70bb9

Resources:

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html
  FileSystem:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      BackupPolicy:
        Status: ENABLED
      PerformanceMode: maxIO
      Encrypted: true
      # FileSystemPolicy:
      #   Version: "2012-10-17"
      #   Statement:
      #     - Effect: "Allow"
      #       Action:
      #         - "elasticfilesystem:ClientMount"
      #       Principal:
      #           AWS: 'arn:aws:iam::111122223333:role/EfsReadOnly'
  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-mounttarget.html
  MountTarget: 
    Type: AWS::EFS::MountTarget
    Properties: 
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref SubnetId
      SecurityGroups: 
        - !GetAtt SG.GroupId