Resources:
  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#aws-resource-iam-user-properties
  MyCfnUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      UserName: 'cfn-user'
      Policies: 
        - PolicyName: CoolPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Sid: IamListAccess
                  Effect: Allow
                  Action:
                  - 'iam:ListRoles'
                  - 'iam:ListUsers'
                  Resource: '*'
  MyInlinePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyInlinePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
            - Sid: IamListAccess
              Effect: Allow
              Action:
              - 'ec2:*'
              Resource: '*'
      Users:
        - !Ref MyCfnUser
  SecondInlinePolicy:
    Type: 'AWS::IAM::UserPolicy'
    Properties:
      PolicyName: SecondInlinePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'
      UserName: !Ref MyCfnUser

            