#!/usr/bin/env bash

#Create VPC
VPC_ID=$(aws ec2 create-vpc --cidr-block "172.33.0.0/16" \
--region ca-central-1 --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=My-Cli-Vpc-10}]' \
--query Vpc.VpcId \
--output text)

echo "VPC_ID : $VPC_ID"

#Turn on DNS host names
aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames "{\"Value\":true}" 

#Create IGW

IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--tag-specifications 'ResourceType=internet-gateway,Tags=[{Key=Name,Value=My-Cli-IGW-10}]' \
--output text)

echo "IGW_ID : $IGW_ID"

#Attach IGW

aws ec2 attach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

#Create Subnets
SUBNET_ID=$(aws ec2 create-subnet --vpc-id $VPC_ID \
--cidr-block 172.33.0.0/20 \
--query Subnet.SubnetId --output text)

#Auto assign  public IP
aws ec2 modify-subnet-attribute --subnet-id $SUBNET_ID --map-public-ip-on-launch

echo "SUBNET_ID : $SUBNET_ID"

#Associate Subnets

RTB_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query "RouteTables[].RouteTableId[]" \
--output text)

echo "RTB_ID : $RTB_ID"

aws ec2 associate-route-table \
--route-table-id $RTB_ID \
--subnet-id $SUBNET_ID

# Add a route table to IGW
aws ec2 create-route \
--route-table-id $RTB_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID





