#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "No VPC ID is given"
  exit 1
else 
  export VPC_ID=$1
fi

#Detach IGW and Delete IGW
IGW_ID=$(aws ec2 describe-internet-gateways --filters "Name=attachment.vpc-id,Values=$VPC_ID" \
--query "InternetGateways[*].InternetGatewayId" --output text)
echo $IGW_ID

echo "Detaching the IGW"
aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

echo "Deleting the IGW"
aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

#Delete Subnets

SUBNET_ID=$(aws ec2 describe-subnets \
--filters "Name=vpc-id,Values=$VPC_ID" --query "Subnets[].SubnetId" --output text
)

#Delete Route tables 
RTB_ID=$(aws ec2 describe-route-tables \
--filters "Name=association.subnet-id,Values=$SUBNET_ID" --query "RouteTables[].RouteTableId" --output text
)

ASSOC_ID=$(aws ec2 describe-route-tables \
    --filters "Name=route-table-id,Values=$RTB_ID" "Name=association.subnet-id,Values=$SUBNET_ID" \
    --query "RouteTables[].Associations[?SubnetId=='$SUBNET_ID'].RouteTableAssociationId[]" \
    --output text)

aws ec2 disassociate-route-table --association-id $ASSOC_ID

aws ec2 delete-route --route-table-id $RTB_ID --destination-cidr-block 0.0.0.0/0

# aws ec2 delete-route-table --route-table-id $RTB_ID

aws ec2 delete-subnet --subnet-id $SUBNET_ID

#Delete VPC
aws ec2 delete-vpc --vpc-id $VPC_ID
echo "Deleted the VPC"
