#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "No bucket name is given"
  exit 1
fi

echo "List of Objects in Bucket"

BUCKET_NAME=$1 


aws s3api list-objects \
--bucket $BUCKET_NAME \
--output text